#!/bin/bash
SALMON_VERSION=2.3.0
SRC_ROOT=../../src/python
LICENSE_FILE=../../../LICENSE

OUTPUT_ROOT=../../../output
OUTPUT_DIR=$OUTPUT_ROOT/python
PACKAGES_DIR=packages

# SalmonCore

SALMON_CORE=$SRC_ROOT/salmon_core/salmon_core
SALMON_CORE_TOML=$SRC_ROOT/salmon_core/pyproject.toml
SALMON_CORE_PACKAGE_NAME=salmon_core_py.$SALMON_VERSION
SALMON_CORE_PACKAGE_FILE=$SALMON_CORE_PACKAGE_NAME.tar.gz

mkdir -p $PACKAGES_DIR/$SALMON_CORE_PACKAGE_NAME
rm -rf $PACKAGES_DIR/$SALMON_CORE_PACKAGE_NAME/*
cp -rf $SALMON_CORE $PACKAGES_DIR/$SALMON_CORE_PACKAGE_NAME
cp $SALMON_CORE_TOML $PACKAGES_DIR/$SALMON_CORE_PACKAGE_NAME/
find $PACKAGES_DIR/$SALMON_CORE_PACKAGE_NAME -name "*.pyc" -type f -delete
find $PACKAGES_DIR/$SALMON_CORE_PACKAGE_NAME -name "__pycache__" -type d -delete
cp Salmon.Core.README.md $PACKAGES_DIR/$SALMON_CORE_PACKAGE_NAME/README.md
cp $LICENSE_FILE $PACKAGES_DIR/$SALMON_CORE_PACKAGE_NAME
cd $PACKAGES_DIR && tar -czvf $SALMON_CORE_PACKAGE_FILE $SALMON_CORE_PACKAGE_NAME/
cd .. && mkdir -p $OUTPUT_DIR
cp -f $PACKAGES_DIR/$SALMON_CORE_PACKAGE_FILE $OUTPUT_DIR

# SalmonFS

SALMON_FS=$SRC_ROOT/salmon_fs/salmon_fs
SALMON_FS_TOML=$SRC_ROOT/salmon_fs/pyproject.toml
SALMON_FS_PACKAGE_NAME=salmon_fs_py.$SALMON_VERSION
SALMON_FS_PACKAGE_FILE=$SALMON_FS_PACKAGE_NAME.tar.gz

mkdir -p $PACKAGES_DIR/$SALMON_FS_PACKAGE_NAME
rm -rf $PACKAGES_DIR/$SALMON_FS_PACKAGE_NAME/*
cp -rf $SALMON_FS $PACKAGES_DIR/$SALMON_FS_PACKAGE_NAME
cp $SALMON_FS_TOML $PACKAGES_DIR/$SALMON_FS_PACKAGE_NAME/
find $PACKAGES_DIR/$SALMON_FS_PACKAGE_NAME -name "*.pyc" -type f -delete
find $PACKAGES_DIR/$SALMON_FS_PACKAGE_NAME -name "__pycache__" -type d -delete
cp Salmon.FS.README.md $PACKAGES_DIR/$SALMON_FS_PACKAGE_NAME/README.md
cp $LICENSE_FILE $PACKAGES_DIR/$SALMON_FS_PACKAGE_NAME
cd $PACKAGES_DIR && tar -czvf $SALMON_FS_PACKAGE_FILE $SALMON_FS_PACKAGE_NAME/
cd .. && mkdir -p $OUTPUT_DIR
cp -f $PACKAGES_DIR/$SALMON_FS_PACKAGE_FILE $OUTPUT_DIR