#!/bin/bash
SRC_ROOT=../../src/python
SALMON_CORE=$SRC_ROOT/salmon_core/salmon_core
SALMON_CORE_TOML=$SRC_ROOT/salmon_core/pyproject.toml

OUTPUT_ROOT=../../../output
OUTPUT_DIR=$OUTPUT_ROOT/python

VERSION=1.0.6-SNAPSHOT
PACKAGES_DIR=packages
SALMON_CORE_PACKAGE_NAME=salmon_core_py.$VERSION

SALMON_CORE_PACKAGE_FILE=$SALMON_CORE_PACKAGE_NAME.tar.gz

mkdir -p $PACKAGES_DIR/$SALMON_CORE_PACKAGE_NAME
rm -rf $PACKAGES_DIR/$SALMON_CORE_PACKAGE_NAME/*

cp -rf $SALMON_CORE $PACKAGES_DIR/$SALMON_CORE_PACKAGE_NAME
cp $SALMON_CORE_TOML $PACKAGES_DIR/$SALMON_CORE_PACKAGE_NAME/
find $PACKAGES_DIR/$SALMON_CORE_PACKAGE_NAME -name "*.pyc" -type f -delete
find $PACKAGES_DIR/$SALMON_CORE_PACKAGE_NAME -name "__pycache__" -type d -delete
cp README.md $PACKAGES_DIR/$SALMON_CORE_PACKAGE_NAME
cp ../../../LICENSE $PACKAGES_DIR/$SALMON_CORE_PACKAGE_NAME

cd $PACKAGES_DIR && tar -czvf $SALMON_CORE_PACKAGE_FILE $SALMON_CORE_PACKAGE_NAME/
cd .. && mkdir -p $OUTPUT_DIR
cp -f $PACKAGES_DIR/$SALMON_CORE_PACKAGE_FILE $OUTPUT_DIR