#!/bin/bash
SALMON_VERSION=3.0.2
SIMPLEIO_VERSION=1.0.2
SIMPLEFS_VERSION=1.0.2
SRC_ROOT=../../src/python
LICENSE_FILE=../../../LICENSE

OUTPUT_ROOT=../../../output
PY_OUTPUT_DIR=$OUTPUT_ROOT/python

mkdir -p $PY_OUTPUT_DIR

# SimpleIO

SIMPLE_IO=$SRC_ROOT/simple_io/simple_io
SIMPLE_IO_TOML=$SRC_ROOT/simple_io/pyproject.toml
SIMPLE_IO_PACKAGE_NAME=simple_io_py.$SIMPLEIO_VERSION
SIMPLE_IO_PACKAGE_FILE=$SIMPLE_IO_PACKAGE_NAME.tar.gz

mkdir -p $PY_OUTPUT_DIR/$SIMPLE_IO_PACKAGE_NAME
rm -rf $PY_OUTPUT_DIR/$SIMPLE_IO_PACKAGE_NAME/*
cp -rf $SIMPLE_IO $PY_OUTPUT_DIR/$SIMPLE_IO_PACKAGE_NAME
cp $SIMPLE_IO_TOML $PY_OUTPUT_DIR/$SIMPLE_IO_PACKAGE_NAME/
find $PY_OUTPUT_DIR/$SIMPLE_IO_PACKAGE_NAME -name "*.pyc" -type f -delete
find $PY_OUTPUT_DIR/$SIMPLE_IO_PACKAGE_NAME -name "__pycache__" -type d -delete
cp SimpleIO.README.md $PY_OUTPUT_DIR/$SIMPLE_IO_PACKAGE_NAME/README.md
cp $LICENSE_FILE $PY_OUTPUT_DIR/$SIMPLE_IO_PACKAGE_NAME
tar -czvf $PY_OUTPUT_DIR/$SIMPLE_IO_PACKAGE_FILE -C $PY_OUTPUT_DIR $SIMPLE_IO_PACKAGE_NAME/

# SimpleFS

SIMPLE_FS=$SRC_ROOT/simple_fs/simple_fs
SIMPLE_FS_TOML=$SRC_ROOT/simple_fs/pyproject.toml
SIMPLE_FS_PACKAGE_NAME=simple_fs_py.$SIMPLEFS_VERSION
SIMPLE_FS_PACKAGE_FILE=$SIMPLE_FS_PACKAGE_NAME.tar.gz

mkdir -p $PY_OUTPUT_DIR/$SIMPLE_FS_PACKAGE_NAME
rm -rf $PY_OUTPUT_DIR/$SIMPLE_FS_PACKAGE_NAME/*
cp -rf $SIMPLE_FS $PY_OUTPUT_DIR/$SIMPLE_FS_PACKAGE_NAME
cp $SIMPLE_FS_TOML $PY_OUTPUT_DIR/$SIMPLE_FS_PACKAGE_NAME/
find $PY_OUTPUT_DIR/$SIMPLE_FS_PACKAGE_NAME -name "*.pyc" -type f -delete
find $PY_OUTPUT_DIR/$SIMPLE_FS_PACKAGE_NAME -name "__pycache__" -type d -delete
cp SimpleFS.README.md $PY_OUTPUT_DIR/$SIMPLE_FS_PACKAGE_NAME/README.md
cp $LICENSE_FILE $PY_OUTPUT_DIR/$SIMPLE_FS_PACKAGE_NAME
tar -czvf $PY_OUTPUT_DIR/$SIMPLE_FS_PACKAGE_FILE -C $PY_OUTPUT_DIR $SIMPLE_FS_PACKAGE_NAME/

# SalmonCore

SALMON_CORE=$SRC_ROOT/salmon_core/salmon_core
SALMON_CORE_TOML=$SRC_ROOT/salmon_core/pyproject.toml
SALMON_CORE_PACKAGE_NAME=salmon_core_py.$SALMON_VERSION
SALMON_CORE_PACKAGE_FILE=$SALMON_CORE_PACKAGE_NAME.tar.gz

mkdir -p $PY_OUTPUT_DIR/$SALMON_CORE_PACKAGE_NAME
rm -rf $PY_OUTPUT_DIR/$SALMON_CORE_PACKAGE_NAME/*
cp -rf $SALMON_CORE $PY_OUTPUT_DIR/$SALMON_CORE_PACKAGE_NAME
cp $SALMON_CORE_TOML $PY_OUTPUT_DIR/$SALMON_CORE_PACKAGE_NAME/
find $PY_OUTPUT_DIR/$SALMON_CORE_PACKAGE_NAME -name "*.pyc" -type f -delete
find $PY_OUTPUT_DIR/$SALMON_CORE_PACKAGE_NAME -name "__pycache__" -type d -delete
cp Salmon.Core.README.md $PY_OUTPUT_DIR/$SALMON_CORE_PACKAGE_NAME/README.md
cp $LICENSE_FILE $PY_OUTPUT_DIR/$SALMON_CORE_PACKAGE_NAME
tar -czvf $PY_OUTPUT_DIR/$SALMON_CORE_PACKAGE_FILE -C $PY_OUTPUT_DIR $SALMON_CORE_PACKAGE_NAME/

# SalmonFS

SALMON_FS=$SRC_ROOT/salmon_fs/salmon_fs
SALMON_FS_TOML=$SRC_ROOT/salmon_fs/pyproject.toml
SALMON_FS_PACKAGE_NAME=salmon_fs_py.$SALMON_VERSION
SALMON_FS_PACKAGE_FILE=$SALMON_FS_PACKAGE_NAME.tar.gz

mkdir -p $PY_OUTPUT_DIR/$SALMON_FS_PACKAGE_NAME
rm -rf $PY_OUTPUT_DIR/$SALMON_FS_PACKAGE_NAME/*
cp -rf $SALMON_FS $PY_OUTPUT_DIR/$SALMON_FS_PACKAGE_NAME
cp $SALMON_FS_TOML $PY_OUTPUT_DIR/$SALMON_FS_PACKAGE_NAME/
find $PY_OUTPUT_DIR/$SALMON_FS_PACKAGE_NAME -name "*.pyc" -type f -delete
find $PY_OUTPUT_DIR/$SALMON_FS_PACKAGE_NAME -name "__pycache__" -type d -delete
cp Salmon.FS.README.md $PY_OUTPUT_DIR/$SALMON_FS_PACKAGE_NAME/README.md
cp $LICENSE_FILE $PY_OUTPUT_DIR/$SALMON_FS_PACKAGE_NAME
tar -czvf $PY_OUTPUT_DIR/$SALMON_FS_PACKAGE_FILE -C $PY_OUTPUT_DIR $SALMON_FS_PACKAGE_NAME/