#!/bin/bash
SRC_ROOT=../../src/python
SALMON_FS=$SRC_ROOT/salmon_fs/salmon_fs
SALMON_FS_TOML=$SRC_ROOT/salmon_fs/pyproject.toml

OUTPUT_ROOT=../../../output
OUTPUT_DIR=$OUTPUT_ROOT/python

VERSION=2.2.0
PACKAGES_DIR=packages
SALMON_FS_PACKAGE_NAME=salmon_fs_py.$VERSION

SALMON_FS_PACKAGE_FILE=$SALMON_FS_PACKAGE_NAME.tar.gz

mkdir -p $PACKAGES_DIR/$SALMON_FS_PACKAGE_NAME
rm -rf $PACKAGES_DIR/$SALMON_FS_PACKAGE_NAME/*

cp -rf $SALMON_FS $PACKAGES_DIR/$SALMON_FS_PACKAGE_NAME
cp $SALMON_FS_TOML $PACKAGES_DIR/$SALMON_FS_PACKAGE_NAME/
find $PACKAGES_DIR/$SALMON_FS_PACKAGE_NAME -name "*.pyc" -type f -delete
find $PACKAGES_DIR/$SALMON_FS_PACKAGE_NAME -name "__pycache__" -type d -delete
cp Salmon.FS.README.md $PACKAGES_DIR/$SALMON_FS_PACKAGE_NAME/README.md
cp ../../../LICENSE $PACKAGES_DIR/$SALMON_FS_PACKAGE_NAME

cd $PACKAGES_DIR && tar -czvf $SALMON_FS_PACKAGE_FILE $SALMON_FS_PACKAGE_NAME/
cd .. && mkdir -p $OUTPUT_DIR
cp -f $PACKAGES_DIR/$SALMON_FS_PACKAGE_FILE $OUTPUT_DIR