#!/bin/bash
SALMON_VERSION=3.0.1
SRC_ROOT=../../src/python
LICENSE_FILE=../../../LICENSE

OUTPUT_ROOT=../../../output
PY_OUTPUT_DIR=$OUTPUT_ROOT/python

mkdir -p $PY_OUTPUT_DIR

# SalmonCore

SALMON_CORE=$SRC_ROOT/salmon_core/salmon_core
SALMON_CORE_TOML=$SRC_ROOT/salmon_core/pyproject.toml
SALMON_CORE_PACKAGE_NAME=salmon_core_py.$SALMON_VERSION
SALMON_CORE_PACKAGE_FILE=$SALMON_CORE_PACKAGE_NAME.tar.gz

mkdir -p $PY_OUTPUT_DIR/$SALMON_CORE_PACKAGE_NAME
rm -rf $PY_OUTPUT_DIR/$SALMON_CORE_PACKAGE_NAME/*
cp -rf $SALMON_CORE $PY_OUTPUT_DIR/$SALMON_CORE_PACKAGE_NAME
cp $SALMON_CORE_TOML $PY_OUTPUT_DIR/$SALMON_CORE_PACKAGE_NAME/
find $PY_OUTPUT_DIR/$SALMON_CORE_PACKAGE_NAME -name "*.pyc" -type f -delete
find $PY_OUTPUT_DIR/$SALMON_CORE_PACKAGE_NAME -name "__pycache__" -type d -delete
cp Salmon.Core.README.md $PY_OUTPUT_DIR/$SALMON_CORE_PACKAGE_NAME/README.md
cp $LICENSE_FILE $PY_OUTPUT_DIR/$SALMON_CORE_PACKAGE_NAME
tar -czvf $PY_OUTPUT_DIR/$SALMON_CORE_PACKAGE_FILE -C $PY_OUTPUT_DIR $SALMON_CORE_PACKAGE_NAME/

# SalmonFS

SALMON_FS=$SRC_ROOT/salmon_fs/salmon_fs
SALMON_FS_TOML=$SRC_ROOT/salmon_fs/pyproject.toml
SALMON_FS_PACKAGE_NAME=salmon_fs_py.$SALMON_VERSION
SALMON_FS_PACKAGE_FILE=$SALMON_FS_PACKAGE_NAME.tar.gz

mkdir -p $PY_OUTPUT_DIR/$SALMON_FS_PACKAGE_NAME
rm -rf $PY_OUTPUT_DIR/$SALMON_FS_PACKAGE_NAME/*
cp -rf $SALMON_FS $PY_OUTPUT_DIR/$SALMON_FS_PACKAGE_NAME
cp $SALMON_FS_TOML $PY_OUTPUT_DIR/$SALMON_FS_PACKAGE_NAME/
find $PY_OUTPUT_DIR/$SALMON_FS_PACKAGE_NAME -name "*.pyc" -type f -delete
find $PY_OUTPUT_DIR/$SALMON_FS_PACKAGE_NAME -name "__pycache__" -type d -delete
cp Salmon.FS.README.md $PY_OUTPUT_DIR/$SALMON_FS_PACKAGE_NAME/README.md
cp $LICENSE_FILE $PY_OUTPUT_DIR/$SALMON_FS_PACKAGE_NAME
tar -czvf $PY_OUTPUT_DIR/$SALMON_FS_PACKAGE_FILE -C $PY_OUTPUT_DIR $SALMON_FS_PACKAGE_NAME/