SET FILEPATH=salmon-aes-kernel.cpp

echo // auto-generated by gen_kernel_source.bat > %FILEPATH%
echo extern ^"C^" const char* KERNEL_SRC = R^"( >> %FILEPATH%
type "..\..\..\src\c\salmon\src\salmon-aes.c" >> %FILEPATH%
type "..\..\..\src\c\salmon\src\salmon-aes-kernel.cl" >> %FILEPATH%
echo )^"; >> %FILEPATH%