SET FILEPATH=salmon-aes-kernel.c

echo // auto-generated by gen_kernel_source.bat > %FILEPATH%
echo const char* KERNEL_SRC = R^"( >> %FILEPATH%
type "..\..\src\c\salmon\src\salmon-aes.c" >> %FILEPATH%
type "..\..\src\c\salmon\src\salmon-aes-kernel.cl" >> %FILEPATH%
echo )^"; >> %FILEPATH%