#!/bin/bash
SALMON_VERSION=3.0.2
SIMPLEIO_VERSION=1.0.2
SIMPLEFS_VERSION=1.0.2
CURRDIR=$(pwd)

TS_SRC_ROOT=../../src/typescript
JS_SRC_ROOT=./lib
OUTPUT_ROOT=$CURRDIR/../../../output
TS_OUTPUT_DIR=$OUTPUT_ROOT/typescript
JS_OUTPUT_DIR=$OUTPUT_ROOT/javascript
DOCS=./docs

SIMPLEIO=simple-io
SIMPLEFS=simple-fs
SALMON_CORE=salmon-core
SALMON_FS=salmon-fs
TS_SIMPLEIO_PACKAGE_NAME=$SIMPLEIO.ts.$SIMPLEIO_VERSION
TS_SIMPLEFS_PACKAGE_NAME=$SIMPLEFS.ts.$SIMPLEFS_VERSION
TS_SALMON_CORE_PACKAGE_NAME=$SALMON_CORE.ts.$SALMON_VERSION
TS_SALMON_FS_PACKAGE_NAME=$SALMON_FS.ts.$SALMON_VERSION

JS_SIMPLEIO_PACKAGE_NAME=$SIMPLEIO.js.$SIMPLEIO_VERSION
JS_SIMPLEFS_PACKAGE_NAME=$SIMPLEFS.js.$SIMPLEFS_VERSION
JS_SALMON_CORE_PACKAGE_NAME=$SALMON_CORE.js.$SALMON_VERSION
JS_SALMON_FS_PACKAGE_NAME=$SALMON_FS.js.$SALMON_VERSION

mkdir -p $TS_OUTPUT_DIR
mkdir -p $JS_OUTPUT_DIR

# TYPESCRIPT

# Typescript SimpleIO
mkdir -p $TS_OUTPUT_DIR/$TS_SIMPLEIO_PACKAGE_NAME
rm -rf $TS_OUTPUT_DIR/$TS_SIMPLEIO_PACKAGE_NAME/*
cp -r $TS_SRC_ROOT/$SIMPLEIO $TS_OUTPUT_DIR/$TS_SIMPLEIO_PACKAGE_NAME
cp $DOCS/SimpleIO.README.txt $TS_OUTPUT_DIR/$TS_SIMPLEIO_PACKAGE_NAME/README.txt
cd $TS_OUTPUT_DIR/$TS_SIMPLEIO_PACKAGE_NAME
rm -f ../$TS_SIMPLEIO_PACKAGE_NAME.zip
zip -r ../$TS_SIMPLEIO_PACKAGE_NAME.zip *
cd $CURRDIR

# Typescript SimpleFS
mkdir -p $TS_OUTPUT_DIR/$TS_SIMPLEFS_PACKAGE_NAME
rm -rf $TS_OUTPUT_DIR/$TS_SIMPLEFS_PACKAGE_NAME/*
cp -r $TS_SRC_ROOT/$SIMPLEFS/fs $TS_OUTPUT_DIR/$TS_SIMPLEFS_PACKAGE_NAME/fs
cp $DOCS/SimpleFS.README.txt $TS_OUTPUT_DIR/$TS_SIMPLEFS_PACKAGE_NAME/README.txt
cd $TS_OUTPUT_DIR/$TS_SIMPLEFS_PACKAGE_NAME
rm -f ../$TS_SIMPLEFS_PACKAGE_NAME.zip
zip -r ../$TS_SIMPLEFS_PACKAGE_NAME.zip *
cd $CURRDIR

# Typescript SalmonCore
mkdir -p $TS_OUTPUT_DIR/$TS_SALMON_CORE_PACKAGE_NAME
rm -rf $TS_OUTPUT_DIR/$TS_SALMON_CORE_PACKAGE_NAME/*
cp -r $TS_SRC_ROOT/$SALMON_CORE $TS_OUTPUT_DIR/$TS_SALMON_CORE_PACKAGE_NAME
cp $DOCS/Salmon.Core.README.txt $TS_OUTPUT_DIR/$TS_SALMON_CORE_PACKAGE_NAME/README.txt
cd $TS_OUTPUT_DIR/$TS_SALMON_CORE_PACKAGE_NAME
rm -f ../$TS_SALMON_CORE_PACKAGE_NAME.zip
zip -r ../$TS_SALMON_CORE_PACKAGE_NAME.zip *
cd $CURRDIR

# Typescript SalmonFS
mkdir -p $TS_OUTPUT_DIR/$TS_SALMON_FS_PACKAGE_NAME
rm -rf $TS_OUTPUT_DIR/$TS_SALMON_FS_PACKAGE_NAME/*
cp -r $TS_SRC_ROOT/$SALMON_FS/salmonfs $TS_OUTPUT_DIR/$TS_SALMON_FS_PACKAGE_NAME/salmonfs
cp -r $TS_SRC_ROOT/$SALMON_FS/service $TS_OUTPUT_DIR/$TS_SALMON_FS_PACKAGE_NAME/service
cp $DOCS/Salmon.FS.README.txt $TS_OUTPUT_DIR/$TS_SALMON_FS_PACKAGE_NAME/README.txt
cd $TS_OUTPUT_DIR/$TS_SALMON_FS_PACKAGE_NAME
rm -f ../$TS_SALMON_FS_PACKAGE_NAME.zip
zip -r ../$TS_SALMON_FS_PACKAGE_NAME.zip *
cd $CURRDIR

# JAVASCRIPT

# JavaScript SimpleIO
mkdir -p $JS_OUTPUT_DIR/$JS_SIMPLEIO_PACKAGE_NAME
rm -rf $JS_OUTPUT_DIR/$JS_SIMPLEIO_PACKAGE_NAME/*
cp -r $JS_SRC_ROOT/$SIMPLEIO $JS_OUTPUT_DIR/$JS_SIMPLEIO_PACKAGE_NAME
cp $DOCS/SimpleIO.README.txt $JS_OUTPUT_DIR/$JS_SIMPLEIO_PACKAGE_NAME/README.txt
cd $JS_OUTPUT_DIR/$JS_SIMPLEIO_PACKAGE_NAME
rm -f ../$JS_SIMPLEIO_PACKAGE_NAME.zip
zip -r ../$JS_SIMPLEIO_PACKAGE_NAME.zip *
cd $CURRDIR

# JavaScript SimpleFS
mkdir -p $JS_OUTPUT_DIR/$JS_SIMPLEFS_PACKAGE_NAME
rm -rf $JS_OUTPUT_DIR/$JS_SIMPLEFS_PACKAGE_NAME/*
cp -r $JS_SRC_ROOT/$SIMPLEFS $JS_OUTPUT_DIR/$JS_SIMPLEFS_PACKAGE_NAME
cp $DOCS/SimpleFS.README.txt $JS_OUTPUT_DIR/$JS_SIMPLEFS_PACKAGE_NAME/README.txt
cd $JS_OUTPUT_DIR/$JS_SIMPLEFS_PACKAGE_NAME
rm -f ../$JS_SIMPLEFS_PACKAGE_NAME.zip
zip -r ../$JS_SIMPLEFS_PACKAGE_NAME.zip *
cd $CURRDIR

# JavaScript SalmonCore
mkdir -p $JS_OUTPUT_DIR/$JS_SALMON_CORE_PACKAGE_NAME
rm -rf $JS_OUTPUT_DIR/$JS_SALMON_CORE_PACKAGE_NAME/*
cp -r $JS_SRC_ROOT/$SALMON_CORE $JS_OUTPUT_DIR/$JS_SALMON_CORE_PACKAGE_NAME
cp $DOCS/Salmon.Core.README.txt $JS_OUTPUT_DIR/$JS_SALMON_CORE_PACKAGE_NAME/README.txt
cd $JS_OUTPUT_DIR/$JS_SALMON_CORE_PACKAGE_NAME
rm -f ../$JS_SALMON_CORE_PACKAGE_NAME.zip
zip -r ../$JS_SALMON_CORE_PACKAGE_NAME.zip *
cd $CURRDIR

# Javascript SalmonFS
mkdir -p $JS_OUTPUT_DIR/$JS_SALMON_FS_PACKAGE_NAME
rm -rf $JS_OUTPUT_DIR/$JS_SALMON_FS_PACKAGE_NAME/*
cp -r $JS_SRC_ROOT/$SALMON_FS $JS_OUTPUT_DIR/$JS_SALMON_FS_PACKAGE_NAME
cp $DOCS/Salmon.FS.README.txt $JS_OUTPUT_DIR/$JS_SALMON_FS_PACKAGE_NAME/README.txt
cd $JS_OUTPUT_DIR/$JS_SALMON_FS_PACKAGE_NAME
rm -f ../$JS_SALMON_FS_PACKAGE_NAME.zip
zip -r ../$JS_SALMON_FS_PACKAGE_NAME.zip *
cd $CURRDIR