#!/bin/bash
SALMON_VERSION=2.3.0
TS_SRC_ROOT=../../src/typescript
JS_SRC_ROOT=./lib
OUTPUT_ROOT=../../../output
TS_OUTPUT_DIR=$OUTPUT_ROOT/typescript
JS_OUTPUT_DIR=$OUTPUT_ROOT/javascript
DOCS=./docs

PACKAGES_DIR=packages
SALMON_CORE=salmon-core
SALMON_FS=salmon-fs
TS_SALMON_CORE_PACKAGE_NAME=$SALMON_CORE.ts.$SALMON_VERSION
TS_SALMON_FS_PACKAGE_NAME=$SALMON_FS.ts.$SALMON_VERSION
JS_SALMON_CORE_PACKAGE_NAME=$SALMON_CORE.js.$SALMON_VERSION
JS_SALMON_FS_PACKAGE_NAME=$SALMON_FS.js.$SALMON_VERSION

mkdir -p $PACKAGES_DIR
rm -rf $PACKAGES_DIR/*

# Typescript SalmonCore
mkdir -p $PACKAGES_DIR/$TS_SALMON_CORE_PACKAGE_NAME
rm -rf $PACKAGES_DIR/$TS_SALMON_CORE_PACKAGE_NAME/*
cp -r $TS_SRC_ROOT/$SALMON_CORE $PACKAGES_DIR/$TS_SALMON_CORE_PACKAGE_NAME
cp $DOCS/Salmon.Core.README.txt $PACKAGES_DIR/$TS_SALMON_CORE_PACKAGE_NAME/README.txt
cd $PACKAGES_DIR/$TS_SALMON_CORE_PACKAGE_NAME
zip -r ../$TS_SALMON_CORE_PACKAGE_NAME.zip *
cd ../../
mkdir -p $TS_OUTPUT_DIR
cp -f $PACKAGES_DIR/$TS_SALMON_CORE_PACKAGE_NAME.zip $TS_OUTPUT_DIR

# Typescript SalmonFS
mkdir -p $PACKAGES_DIR/$TS_SALMON_FS_PACKAGE_NAME
rm -rf $PACKAGES_DIR/$TS_SALMON_FS_PACKAGE_NAME/*
cp -r $TS_SRC_ROOT/$SALMON_FS $PACKAGES_DIR/$TS_SALMON_FS_PACKAGE_NAME
cp $DOCS/Salmon.FS.README.txt $PACKAGES_DIR/$TS_SALMON_FS_PACKAGE_NAME/README.txt
cd $PACKAGES_DIR/$TS_SALMON_FS_PACKAGE_NAME
zip -r ../$TS_SALMON_FS_PACKAGE_NAME.zip *
cd ../../
mkdir -p $TS_OUTPUT_DIR
cp -f $PACKAGES_DIR/$TS_SALMON_FS_PACKAGE_NAME.zip $TS_OUTPUT_DIR

# Javascript SalmonCore
mkdir -p $PACKAGES_DIR/$JS_SALMON_CORE_PACKAGE_NAME
rm -rf $PACKAGES_DIR/$JS_SALMON_CORE_PACKAGE_NAME/*
cp -r $JS_SRC_ROOT/$SALMON_CORE $PACKAGES_DIR/$JS_SALMON_CORE_PACKAGE_NAME
cp $DOCS/Salmon.Core.README.txt $PACKAGES_DIR/$JS_SALMON_CORE_PACKAGE_NAME/README.txt
cd $PACKAGES_DIR/$JS_SALMON_CORE_PACKAGE_NAME
zip -r ../$JS_SALMON_CORE_PACKAGE_NAME.zip *
cd ../../
mkdir -p $JS_OUTPUT_DIR
cp -f $PACKAGES_DIR/$JS_SALMON_CORE_PACKAGE_NAME.zip $JS_OUTPUT_DIR

# Javascript SalmonFS
mkdir -p $PACKAGES_DIR/$JS_SALMON_FS_PACKAGE_NAME
rm -rf $PACKAGES_DIR/$JS_SALMON_FS_PACKAGE_NAME/*
cp -r $JS_SRC_ROOT/$SALMON_FS $PACKAGES_DIR/$JS_SALMON_FS_PACKAGE_NAME
cp $DOCS/Salmon.FS.README.txt $PACKAGES_DIR/$JS_SALMON_FS_PACKAGE_NAME/README.txt
cd $PACKAGES_DIR/$JS_SALMON_FS_PACKAGE_NAME
zip -r ../$JS_SALMON_FS_PACKAGE_NAME.zip *
cd ../../
mkdir -p $JS_OUTPUT_DIR
cp -f $PACKAGES_DIR/$JS_SALMON_FS_PACKAGE_NAME.zip $JS_OUTPUT_DIR
