# generate the GPU kernel code for use with MS VC++ compilers and gradle
FILEPATH=./salmon/src/kernels/salmon-aes-kernel.cpp

echo '// auto-generated by gen_kernel_source_cpp.sh' > $FILEPATH
echo 'extern "C" const char* KERNEL_SRC = R"(' >> $FILEPATH
cat "./salmon/src/salmon-aes.c" >> $FILEPATH
cat "./salmon/src/kernels/salmon-aes-kernel.cl" >> $FILEPATH
echo ')";' >> $FILEPATH