# generate the GPU kernel code for use with gcc
FILEPATH=./salmon/src/kernels/salmon-aes-kernel.c

echo '// auto-generated by gen_kernel_source_c.sh' > $FILEPATH
echo 'const char* KERNEL_SRC = R"(' >> $FILEPATH
cat "./salmon/src/salmon-aes.c" >> $FILEPATH
cat "./salmon/src/kernels/salmon-aes-kernel.cl" >> $FILEPATH
echo ')";' >> $FILEPATH