:: generate the GPU kernel code for use with MS VC++ compilers and gradle
SET FILEPATH=.\salmon\src\kernels\salmon-aes-kernel.cpp

echo // auto-generated by gen_kernel_source_cpp.bat > %FILEPATH%
echo extern ^"C^" const char* KERNEL_SRC = R^"( >> %FILEPATH%
type ".\salmon\src\salmon-aes.c" >> %FILEPATH%
type ".\salmon\src\kernels\salmon-aes-kernel.cl" >> %FILEPATH%
echo )^"; >> %FILEPATH%