:: generate the GPU kernel code for use with gcc
SET FILEPATH=.\salmon\src\kernels\salmon-aes-kernel.c

echo // auto-generated by gen_kernel_source_c.bat > %FILEPATH%
echo const char* KERNEL_SRC = R^"( >> %FILEPATH%
type ".\salmon\src\salmon-aes.c" >> %FILEPATH%
type ".\salmon\src\kernels\salmon-aes-kernel.cl" >> %FILEPATH%
echo )^"; >> %FILEPATH%