#!/bin/bash
SALMON_VERSION=2.3.0

JAVA_WS=salmon-ws
WS_APP_PROPERTIES=./salmon-ws/config/application.properties
WS_SCRIPT_SH=./scripts/start-salmon-ws.sh
WS_SCRIPT_BAT=./scripts/start-salmon-ws.bat
WS_WAR=./build/libs/$JAVA_WS-$SALMON_VERSION.war

PACKAGES_DIR=packages
CONFIG_DIR=$PACKAGES_DIR/config
OUTPUT_ROOT=../../../../output

WS_OUTPUT_DIR=$OUTPUT_ROOT/$JAVA_WS
WS_PACKAGE_NAME=$JAVA_WS.ts.$SALMON_VERSION

mkdir -p $PACKAGES_DIR
rm -rf $PACKAGES_DIR/*

# Web Service

mkdir -p $PACKAGES_DIR/$WS_PACKAGE_NAME
rm -rf $PACKAGES_DIR/$WS_PACKAGE_NAME/*
mkdir -p $CONFIG_DIR
cp $WS_SCRIPT_BAT $PACKAGES_DIR/$WS_PACKAGE_NAME
cp $WS_SCRIPT_SH $PACKAGES_DIR/$WS_PACKAGE_NAME
cp $WS_WAR $PACKAGES_DIR/$WS_PACKAGE_NAME
cp $WS_APP_PROPERTIES $CONFIG_DIR
cp README.txt $PACKAGES_DIR/$WS_PACKAGE_NAME/README.txt
cd $PACKAGES_DIR/$WS_PACKAGE_NAME
zip -r ../$WS_PACKAGE_NAME.zip *
cd ../../
mkdir -p $WS_OUTPUT_DIR
cp -f $PACKAGES_DIR/$WS_PACKAGE_NAME.zip $WS_OUTPUT_DIR