# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    defaults:
      run:
        working-directory: ./libs/projects/SalmonLibs.VS2022
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Restore workload dependencies
      working-directory: ./libs/projects/SalmonLibs.VS2022/Salmon.Core
      run: dotnet workload restore
    - name: Restore dependencies
      working-directory: ./libs/projects/SalmonLibs.VS2022/Salmon.Core
      run: dotnet restore
    - name: Build
      working-directory: ./libs/projects/SalmonLibs.VS2022/Salmon.Core
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./libs/projects/SalmonLibs.VS2022
      run: dotnet test --no-build --verbosity normal
