# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java Gradle Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: libs/projects/salmon-libs-gradle

    steps:
    - uses: actions/checkout@v4
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}
        restore-keys: |
          gradle-${{ runner.os }}
          gradle-
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: set exec permissions
      run: chmod +x ./gradlew
      
    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    # build and test without native and windows deps
    - name: Build Salmon native with Gradle Wrapper
      run: ./gradlew :salmon-native:build -i
      
    - name: Build with Gradle Wrapper
      run: ./gradlew build -i -x :salmon-win:build -x test
      
    - name: Salmon.Core Test
      run: ./gradlew :salmon-core:test --tests "com.mku.salmon.test.SalmonCoreTests" -i
    - name: Salmon.FS Test
      run: ./gradlew :salmon-fs:test -i -DtestDir="/tmp/salmon/test"
    - name: Salmon.Native Test
      run: ./gradlew :salmon-native:test -i
